first_project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('change-password/', views.change_password_view, name='change_password'),
] 

first_project/article/urls.py
from django.urls import path, re_path,register_converter
from django.shortcuts import redirect, reverse
from article import views



app_name = "article"

urlpatterns = [
    path('', views.index,name='index'),
    path('login/', views.article_login,name='login'),
    path('redir/', views.redir,name='redirect'),
    path('high/<id>/<name>/', views.article_highlight,name='high'),
    path('get/', views.get_http_methods,name='get'),
    path('post/', views.post_http_methods,name='post'),
    path('postget/', views.post_get_methods,name='postget'),
    # re_path(r'.*list/(?P<categories>\w+|(\w+\+\w+)+)/', views.article_list, name='cate')
    path('list/<cate:categories>/', views.article_list, name='cate'),
]

first_project/book/urls.py
from django.urls import path
from book import views

app_name = "book"
urlpatterns = [
    path('', views.book,name='index'),
    path('login/<book_id>', views.book_login, name='sso'),
    path('detail/<book_id>/', views.book_detail),
    path('author/', views.book_author),
    path('publish/<int:publish_id>/', views.book_publisher)
]

first_project/csvhandle/urls.py
from django.urls import path
from . import views

app_name = "csvhandle"
urlpatterns = [
    path('', views.index,name="index"),
    path('stream/', views.stream_csv,name="stream"),
]

first_project/jsonconvert/urls.py
from django.urls import path
from . import views

app_name = "jsonconvert"
urlpatterns = [
    path('', views.index,name="index"),
]

first_project/login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('',views.index,name="index"),
    path('login/',views.login,name="login"),
    path('submit_form/',views.submit_form,name="submit_form")
]

first_project/movie/urls.py
from django.urls import path
from movie import views

#APP应用命名空间
app_name = "movie"

urlpatterns = [
    path('', views.movie,name='index'),
    path('login/', views.movie_login, name='sso'),
    path('high/<id>/', views.movie_highlight, name='high')
]

first_project/uploadfile/urls.py
from django.urls import path
from . import views

app_name = "uploadfile"
urlpatterns = [
    path('', views.index,name="index"),
    path('upload/', views.uploadfile,name="upload"),
    path('display/', views.displayfile,name="display"),
    path('content/', views.filedetail,name="content")
    ]

first_project/book/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import redirect, reverse


def book_login(request, book_id):
    return HttpResponse("图书APP登录页:%s" % book_id)


def book(request):
    if request.GET.get("user") == 'alexzhang':
        return HttpResponse("您好:{}\r\n您目前访问的是图书首页".format(request.GET.get("user")))
    else:
        #return redirect('login/1')
        #return redirect(reverse('book:sso', kwargs={"book_id":1}))
        current_namespace = request.resolver_match.namespace
        #return redirect(reverse('{}:sso'.format(current_namespace), kwargs={"book_id":1}))
        login_url = reverse('{}:sso'.format(current_namespace),kwargs={"book_id":1}) + "?next=/"
        return redirect(login_url)


def book_detail(request, book_id):
    text = "图书ID是：{}".format(book_id)
    return HttpResponse(text)


def book_author(request):
    author_id = request.GET.get("id")
    text = "作者的ID是：{}".format(author_id)
    return HttpResponse(text)


def book_publisher(request, publish_id):
    text = "出版社ID是：%s" % publish_id
    return HttpResponse(text)

first_project/jsonconvert/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from django.shortcuts import redirect,reverse
import json


def index(request):
    if request.method == "GET":
        return render(request, "jsonconvert.html",context={"title":"Json格式化"})
    else:
        text = request.POST.get("my-textbox")
        try:
            json_object = json.loads(text)
            print(json_object)
        except ValueError:
            return HttpResponse("非JSON格式数据")
        return HttpResponse(text,content_type='application/json;charset=utf-8')

first_project/login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect,reverse


# Create your views here.


def login(request):
    dir = request.GET.get("next")
    data = {
        "next":dir
    }
    return render(request, 'login.html',context=data)
    # return HttpResponse("欢迎访问登录页面，您的重定向页面是:{}".format(dir))


def index(request):
    token = request.GET.get("token")
    if token:
        return HttpResponse(f"{token}你好，欢迎访问登录首页")
    else:
        url = reverse('login:login') + "?next={}".format(reverse('login:index'))
        return redirect(url)


def submit_form(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        checkbox = request.POST.getlist("tag1")
        print(checkbox)
        token = username
        nexturl = request.POST.get('next')
        url = nexturl + "?token={}".format(token)
        return redirect(url)
        # return HttpResponse(f"Received username: {username} and password: {password}")
    else:
        return HttpResponse("Invalid request method.")

first_project/template_filter/views.py
from django.shortcuts import render
from datetime import datetime

# Create your views here.
def index(request):
    data = {
        "value1":[1,2,3],
        "value2":[4,5,6],
        "time":datetime.now(),
        "default":"hello",
        "default_0":[],
        "default_1":None,
        "floatValue":3.1415926,
        "script":"<script> function showAlert(message) { alert(message);}</script>",
        "alert":"<button onclick=\"showAlert('safe过滤器测试')\">点我</button>",
        "truncate":"创世纪滨海花园",
        "truncate_html":"<p>模板过滤器</p>",
        "date":datetime.now()
    }
    return render(request, "template_filter.html",context=data)

first_project/template_include/views.py
from django.shortcuts import render

# Create your views here.
data = {
    "username":"alexzhang"
}

def index(request):
    return render(request, "template_include.html",context=data)


def company(request):
    return render(request, "company.html")

def campus(request):
    return render(request, "campus.html")

first_project/template_static/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "template_static.html")

first_project/uploadfile/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db import connection,transaction
import json

# Create your views here.
def get_cursor():
    return connection.cursor()

def add_file(filename):
    cursor = get_cursor()
    sql = f"insert into file(filename) values('{filename}')"
    cursor.execute(sql)
    return "success"


def index(request):
    return render(request, "uploadfile_index.html",context={"title":"文件上传"})

def uploadfile(request):
    if request.method == "POST":
        myfile = request.FILES.get('myfile')
        with open(f"./files/{myfile.name}",'wb') as fp:
            for chunk in myfile.chunks():
                fp.write(chunk)
        add_file(myfile)
        return HttpResponse("upload success!")
    else:
        return render(request, "uploadfile.html")



def displayfile(request):
    cursor = get_cursor()
    sql = f"select * from file"
    cursor.execute(sql)
    files = cursor.fetchall()
    return render(request, 'filecontent.html',context={"files":files})



def filedetail(request):
    filename = request.POST.get('uploadfile')
    with open(f"./files/{filename}",'r',encoding='utf-8') as f:
        data = f.read()
    return render(request, "filedetail.html", context={"data":data})

first_project/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    关于我们 {{ phone }}
</body>
</html>

first_project/templates/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}长颈鹿的家{% endblock %}</title>
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">网站名称</a>
            <div class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <span class="nav-item nav-link">欢迎, {{ user.username }}</span>
                    <a class="nav-item nav-link" href="{% url 'accounts:change_password' %}">修改密码</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">退出</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">登录</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:register' %}">注册</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>

first_project/templates/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BOOKS</title>
    <style>
        .nav{
            overflow: hidden;
            margin: 0;
            background-color: gray;
        }

        .nav li{
            float: left;
            list-style: none;
            margin: 0 20px;
        }
    </style>
</head>
<body>
    <ul class="nav">
        <li><a href="/">首页</a></li>
        <li><a href="/book1/?user=alexzhang">读书</a></li>
        <li><a href="{% url 'movie:sso' %}">电影</a></li>
        <li><a href="/article/login/">文章</a></li>
        {% with 'https://tinysoftgiraffe.top/' as site %}
        <li><a href="{% url 'article:redirect' %}?next={{ site }}">外部重定向</a></li>
        {% endwith %}
        <li><a href="{% url 'movie:high' id='2' %}">最热电影</a></li>
        <li><a href="{% url 'article:high' id='2' name='张弛'%}">最热书籍</a></li>
    </ul>
    <p>书籍是人类进步的阶梯</p>
    <ul>
        {% for book in books reversed%}
            <li>{{ book }}</li>
        {% endfor %}
    </ul>
<!-- 
    {% for key,value in person.items%}
        <div>{{key}}:{{value}} 循环次数：{{forloop.counter}}</div>
    {% endfor %} -->

    <table>
        <thead>
            <tr>
                <td>编号</td>
                <td>姓名</td>
                <td>年龄</td>
                <td>性别</td>
            </tr>
        </thead>
        <tbody>
            {% for person in persons%}
                {% if forloop.first %}
                    <tr style="background-color: yellow;">
                {% elif forloop.last %}
                    <tr style="background-color: pink;">
                {% else %}
                    <tr style="background-color: blue;">
                {% endif %}
                    <td>{{forloop.counter}}</td>
                    <td>{{person.name}}</td>
                    <td>{{person.age}}</td>
                    <td>{{person.gender}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- with 标签，定义dtl中的变量 -->
    {% with shz=books.0 %}
        <p>{{ shz }}</p>
    {% endwith %}
    
    {% with books.3 as xyj %}
        <p>{{ xyj }}</p>
    {% endwith %}
    
    {% spaceless %}
        <p>
            <a href="/movie/login/">移除空格标签</a>
        </p>
    {% endspaceless %}
    
    {% autoescape off %}
    {{ info }}
    {% endautoescape %}
    <div><a href='/'>首页</a></div>
    {% verbatim %}
        {{ if }} {% the handsome boy %} is alexzhang
    {% endverbatim %}
    
</body>
</html>

first_project/templates/campus.html
{% extends 'base.html' %}

{% block content %}
这是校园
{% endblock %}

first_project/templates/db_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>图书管理系统</title>
    <link rel="stylesheet" href="{% static 'db_operations/db.css' %}">
</head>
<body>
    <ul class="nav">
        <li><a href="/">首页</a></li>
        <li><a href="{% url 'db:addbook'%}">发布图书</a></li>
    </ul>

    {% block content %}
    {% endblock %}

</body>
</html>

first_project/templates/filecontent.html
{% extends 'nav_base.html' %}
{% block content %}

    <ul class="nav">
        <li><a href="/uploadfile/">文件上传首页</a></li>
    </ul>
    <br>
    <form method="post" action="{% url 'uploadfile:content'%}">
        {% csrf_token %}
        <label for="my-select">选择你想查看的文件</label>
        <select id="uploadfile" name="uploadfile">
            {% for file in files %}
                <option value="{{ file.1 }}" {% if file.1 == selected_option %}selected{% endif %}>{{ file.1 }}</option>
            {% endfor %}
        </select>
        <input type="hidden" name="selected-option" value="{{ selected_option }}">
        <br><br>
        <input type="submit" value="获取文件内容">
    </form>
{% endblock %}

first_project/templates/filedetail.html
{% extends 'nav_base.html' %}
{% block content %}
    <ul class="nav">
        <li><a href="/uploadfile/">文件上传首页</a></li>
    </ul>
    <div style="margin: 10px 20px;">
        <p>{{ data }}</p>
    </div>
{% endblock %}

first_project/templates/first_project.html
{% extends 'nav_base.html' %}
{% block content %}
    <ul class="nav">
        <li><a href="{% url 'movie:index' %}">电影</a></li>
        <li><a href="{% url 'book:index' %}">图书1</a></li>
        <li><a href="{% url 'book:index' %}">图书2</a></li>
        <li><a href="{% url 'article:index' %}">文章</a></li>
        <li><a href="{% url 'login:index' %}">登录</a></li>
        <li><a href="{% url 'template_filter:index' %}">模板过滤器</a></li>
        <li><a href="{% url 'template_include:index' %}">模板继承</a></li>
        <li><a href="{% url 'template_static:index' %}">静态文件</a></li>
        <li><a href="{% url 'db:index' %}">图书管理系统</a></li>
        <li><a href="{% url 'uploadfile:index' %}">文件上传</a></li>
        <li><a href="{% url 'jsonconvert:index' %}">JSON格式化</a></li>
        <li><a href="{% url 'csvhandle:index' %}">csv文件处理</a></li>
        <li><a href="{% url 'csvhandle:stream' %}">csv流式处理</a></li>
    </ul>

    <p>这是首页</p>
{% endblock %}

first_project/templates/header.html
<header>
    <ul class="nav">
        <li><a href="{% url 'template_include:index' %}">首页</a></li>
        <li><a href="{% url 'template_include:company' %}">公司</a></li>
        <li><a href="{% url 'template_include:campus' %}">校园</a></li>
    </ul>
</header>

first_project/templates/jsonconvert.html
{% extends 'nav_base.html' %}
{% block content %}
<ul class="nav">
    <li><a href="/">首页</a></li>
</ul>

<form action="{% url 'jsonconvert:index' %}" method="post" style="margin: 10px  20px;">
    <label for="my-textbox">请输入文本：</label> <br><br>
    <input type="text" id="my-textbox" name="my-textbox" style="width: 500px;height: 100px;"><br><br>
    <button type="submit">提交</button>
</form>
{% endblock %}

first_project/templates/nav_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'nav.css' %}">
    <title>{{ title }}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

first_project/templates/template_include.html
{% extends 'base.html' %}

{% block content %}
{{ block.super }}
这是首页
{% endblock %}

first_project/templates/template_static.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template_static</title>
    <link rel="stylesheet" href="{% static 'index.css' %}">
</head>
<body>
    <p>加载静态资源</p>
    <!-- <img src="/static/django.png" alt=""> -->
    <img src="{% static  'template_static/django.png' %}" alt="">
</body>
</html>

first_project/templates/uploadfile.html
{% extends 'nav_base.html' %}
{% block content %}
    <ul class="nav">
        <li><a href="/uploadfile/">文件上传首页</a></li>
    </ul>
    <div style="margin: 10px 20px;">
        <form action="{% url 'uploadfile:upload' %}" method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="myfile"> <br><br>
            <input type="submit" value="提交">
        </form>
    </div>
{% endblock %}